name: Rust

on:
  push:
    branches: [ "z2p" ]
  pull_request:
    branches: [ "z2p" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Initialize postgres database
        run: |
          chmod +x ./scripts/init_db.sh
          ./scripts/init_db.sh

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose



